### ISSUE TITLE
公开的logseq文档似乎可以被任何人写入

### ISSUE THREAD

**Issue by pengx17** [handuozh/logseq-notes#1]
Hello @handuozh, 我刚才通过 logseq.com 导入了您的笔记代码仓库，结果发现可以直接导入、并实现写入的同步。我觉得这个情况不应是预期行为。😂

@tiensonqin

**Comment by handuozh** [comment]
啊~好可怕~这个我还真不清楚 😮

**Comment by tiensonqin** [comment]
很抱歉，这个我在查，会尽快解决。

**Comment by tiensonqin** [comment]
@pengx17 @handuozh 这个应该已经修复了，你们试下看看刷新后就不能再 push 了，可以 fork 一个。
产品逻辑上还有问题，就是可以添加其他人公开的 repo, 这个我们也尽快修复。
